coverage:
  github_checks:
    annotations: true
  status:
    patch: true
    project:
      default:
        target: 100%
        threshold: 1%
  comment:
    layout: "reach, diff, flags, files"
    behavior: default
    require_changes: false
    require_base: no
    require_head: yes
