name: CI/CD

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16.15.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: "npm install --save --legacy-peer-deps"
      - name: Run lint
        run: "npm run lint"

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16.15.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: "npm install --save --legacy-peer-deps"
      - name: Run tests
        run: "npm run test:coverage"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/clover.xml
          fail_ci_if_error: true
          flags: unit-tests
          name: clean-arch
          verbose: true
